version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - connector_telegram
        - connector_slack
        - database_matrix
        - connector_matrix

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
